package cr.ac.una.prograiv.proyecto.domain;
// Generated 02/11/2016 03:36:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private Integer idchat;
     private String usuario;
     private String experto;
     private String enviado;
     private String recibido;
     private Date tiempo;
     private int sessionId;

    public Chat() {
    }

	
    public Chat(String usuario, String experto, Date tiempo, int sessionId) {
        this.usuario = usuario;
        this.experto = experto;
        this.tiempo = tiempo;
        this.sessionId = sessionId;
    }
    public Chat(String usuario, String experto, String enviado, String recibido, Date tiempo, int sessionId) {
       this.usuario = usuario;
       this.experto = experto;
       this.enviado = enviado;
       this.recibido = recibido;
       this.tiempo = tiempo;
       this.sessionId = sessionId;
    }
   
    public Integer getIdchat() {
        return this.idchat;
    }
    
    public void setIdchat(Integer idchat) {
        this.idchat = idchat;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getExperto() {
        return this.experto;
    }
    
    public void setExperto(String experto) {
        this.experto = experto;
    }
    public String getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(String enviado) {
        this.enviado = enviado;
    }
    public String getRecibido() {
        return this.recibido;
    }
    
    public void setRecibido(String recibido) {
        this.recibido = recibido;
    }
    public Date getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Date tiempo) {
        this.tiempo = tiempo;
    }
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }




}


