package cr.ac.una.prograiv.proyecto.domain;
// Generated 08/10/2016 08:02:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private int idchat;
     private String usuario;
     private String experto;
     private String enviado;
     private String recibido;
     private Date tiempo;

    public Chat() {
    }

	
    public Chat(int idchat) {
        this.idchat = idchat;
    }
    public Chat(int idchat, String usuario, String experto, String enviado, String recibido, Date tiempo) {
       this.idchat = idchat;
       this.usuario = usuario;
       this.experto = experto;
       this.enviado = enviado;
       this.recibido = recibido;
       this.tiempo = tiempo;
    }
   
    public int getIdchat() {
        return this.idchat;
    }
    
    public void setIdchat(int idchat) {
        this.idchat = idchat;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getExperto() {
        return this.experto;
    }
    
    public void setExperto(String experto) {
        this.experto = experto;
    }
    public String getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(String enviado) {
        this.enviado = enviado;
    }
    public String getRecibido() {
        return this.recibido;
    }
    
    public void setRecibido(String recibido) {
        this.recibido = recibido;
    }
    public Date getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Date tiempo) {
        this.tiempo = tiempo;
    }




}


