package cr.ac.una.prograiv.proyecto.domain;
// Generated 02/11/2016 03:36:49 PM by Hibernate Tools 4.3.1



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Integer idFeedBack;
     private String nombreTema;
     private Integer costoXminuto;
     private String observaciones;
     private int estado;
     private Integer estrellas;

    public Feedback() {
    }

	
    public Feedback(String nombreTema, int estado) {
        this.nombreTema = nombreTema;
        this.estado = estado;
    }
    public Feedback(String nombreTema, Integer costoXminuto, String observaciones, int estado, Integer estrellas) {
       this.nombreTema = nombreTema;
       this.costoXminuto = costoXminuto;
       this.observaciones = observaciones;
       this.estado = estado;
       this.estrellas = estrellas;
    }
   
    public Integer getIdFeedBack() {
        return this.idFeedBack;
    }
    
    public void setIdFeedBack(Integer idFeedBack) {
        this.idFeedBack = idFeedBack;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Integer getCostoXminuto() {
        return this.costoXminuto;
    }
    
    public void setCostoXminuto(Integer costoXminuto) {
        this.costoXminuto = costoXminuto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Integer getEstrellas() {
        return this.estrellas;
    }
    
    public void setEstrellas(Integer estrellas) {
        this.estrellas = estrellas;
    }




}


