package cr.ac.una.prograiv.proyecto.domain;
// Generated 24/10/2016 07:11:30 PM by Hibernate Tools 4.3.1



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private int idFeedBack;
     private String nombreTema;
     private Integer costoXminuto;
     private String observaciones;
     private Integer estado;
     private Integer estrellas;

    public Feedback() {
    }

    public Feedback(int idFeedBack, String nombreTema, Integer costoXminuto, String observaciones, Integer estado, Integer estrellas) {
       this.idFeedBack = idFeedBack;
       this.nombreTema = nombreTema;
       this.costoXminuto = costoXminuto;
       this.observaciones = observaciones;
       this.estado = estado;
       this.estrellas = estrellas;
    }
    
    public Feedback(String nombreTema, Integer costoXminuto, String observaciones, Integer estado, Integer estrellas) {
        this.nombreTema = nombreTema;
        this.costoXminuto = costoXminuto;
        this.observaciones = observaciones;
        this.estado = estado;
        this.estrellas = estrellas;
    }
   
    public int getIdFeedBack() {
        return this.idFeedBack;
    }
    
    public void setIdFeedBack(int idFeedBack) {
        this.idFeedBack = idFeedBack;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Integer getCostoXminuto() {
        return this.costoXminuto;
    }
    
    public void setCostoXminuto(Integer costoXminuto) {
        this.costoXminuto = costoXminuto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Integer getEstrellas() {
        return this.estrellas;
    }
    
    public void setEstrellas(Integer estrellas) {
        this.estrellas = estrellas;
    }




}


