package cr.ac.una.prograiv.proyecto.domain;
// Generated 24/10/2016 07:11:30 PM by Hibernate Tools 4.3.1



/**
 * Gestiontemas generated by hbm2java
 */
public class Gestiontemas  implements java.io.Serializable {


     private int idTemas;
     private String nombreTema;
     private Integer costoXminuto;
     private String observaciones;
     private Integer estado;

    public Gestiontemas() {
    }

	
    public Gestiontemas(int idTemas) {
        this.idTemas = idTemas;
    }
    public Gestiontemas(int idTemas, String nombreTema, Integer costoXminuto, String observaciones, Integer estado) {
       this.idTemas = idTemas;
       this.nombreTema = nombreTema;
       this.costoXminuto = costoXminuto;
       this.observaciones = observaciones;
       this.estado = estado;
    }
   
    public int getIdTemas() {
        return this.idTemas;
    }
    
    public void setIdTemas(int idTemas) {
        this.idTemas = idTemas;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Integer getCostoXminuto() {
        return this.costoXminuto;
    }
    
    public void setCostoXminuto(Integer costoXminuto) {
        this.costoXminuto = costoXminuto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


