package cr.ac.una.prograiv.proyecto.domain;
// Generated 02/11/2016 03:36:49 PM by Hibernate Tools 4.3.1



/**
 * Gestiontemas generated by hbm2java
 */
public class Gestiontemas  implements java.io.Serializable {


     private Integer idTemas;
     private String nombreTema;
     private int costoXminuto;
     private String observaciones;
     private int estado;

    public Gestiontemas() {
    }

	
    public Gestiontemas(String nombreTema, int costoXminuto, int estado) {
        this.nombreTema = nombreTema;
        this.costoXminuto = costoXminuto;
        this.estado = estado;
    }
    public Gestiontemas(String nombreTema, int costoXminuto, String observaciones, int estado) {
       this.nombreTema = nombreTema;
       this.costoXminuto = costoXminuto;
       this.observaciones = observaciones;
       this.estado = estado;
    }
   
    public Integer getIdTemas() {
        return this.idTemas;
    }
    
    public void setIdTemas(Integer idTemas) {
        this.idTemas = idTemas;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public int getCostoXminuto() {
        return this.costoXminuto;
    }
    
    public void setCostoXminuto(int costoXminuto) {
        this.costoXminuto = costoXminuto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


