package cr.ac.una.prograiv.proyecto.domain;
// Generated 12/10/2016 05:10:01 PM by Hibernate Tools 4.3.1



/**
 * Historialfacturasxservicio generated by hbm2java
 */
public class Historialfacturasxservicio  implements java.io.Serializable {


     private Integer idhistorialFacturasXservicio;
     private Integer costoServicio;
     private Integer duracion;
     private Integer total;

    public Historialfacturasxservicio() {
    }

    public Historialfacturasxservicio(Integer costoServicio, Integer duracion, Integer total) {
       this.costoServicio = costoServicio;
       this.duracion = duracion;
       this.total = total;
    }
   
    public Integer getIdhistorialFacturasXservicio() {
        return this.idhistorialFacturasXservicio;
    }
    
    public void setIdhistorialFacturasXservicio(Integer idhistorialFacturasXservicio) {
        this.idhistorialFacturasXservicio = idhistorialFacturasXservicio;
    }
    public Integer getCostoServicio() {
        return this.costoServicio;
    }
    
    public void setCostoServicio(Integer costoServicio) {
        this.costoServicio = costoServicio;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }




}


