package cr.ac.una.prograiv.proyecto.domain;
// Generated 02/11/2016 03:36:49 PM by Hibernate Tools 4.3.1



/**
 * Temasexperto generated by hbm2java
 */
public class Temasexperto  implements java.io.Serializable {


     private Integer idTemasExperto;
     private int idExperto;
     private int idTema;
     private String temaNombre;

    public Temasexperto() {
    }

	
    public Temasexperto(int idExperto, int idTema) {
        this.idExperto = idExperto;
        this.idTema = idTema;
    }
    public Temasexperto(int idExperto, int idTema, String temaNombre) {
       this.idExperto = idExperto;
       this.idTema = idTema;
       this.temaNombre = temaNombre;
    }
   
    public Integer getIdTemasExperto() {
        return this.idTemasExperto;
    }
    
    public void setIdTemasExperto(Integer idTemasExperto) {
        this.idTemasExperto = idTemasExperto;
    }
    public int getIdExperto() {
        return this.idExperto;
    }
    
    public void setIdExperto(int idExperto) {
        this.idExperto = idExperto;
    }
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public String getTemaNombre() {
        return this.temaNombre;
    }
    
    public void setTemaNombre(String temaNombre) {
        this.temaNombre = temaNombre;
    }




}


