package cr.ac.una.prograiv.proyecto.domain;
// Generated 24/10/2016 07:11:30 PM by Hibernate Tools 4.3.1



/**
 * Temasexperto generated by hbm2java
 */
public class Temasexperto  implements java.io.Serializable {


     private int idTemasExperto;
     private Integer idExperto;
     private Integer idTema;

    public Temasexperto() {
    }

	
    public Temasexperto(int idTemasExperto) {
        this.idTemasExperto = idTemasExperto;
    }
    public Temasexperto(int idTemasExperto, Integer idExperto, Integer idTema) {
       this.idTemasExperto = idTemasExperto;
       this.idExperto = idExperto;
       this.idTema = idTema;
    }
   
    public int getIdTemasExperto() {
        return this.idTemasExperto;
    }
    
    public void setIdTemasExperto(int idTemasExperto) {
        this.idTemasExperto = idTemasExperto;
    }
    public Integer getIdExperto() {
        return this.idExperto;
    }
    
    public void setIdExperto(Integer idExperto) {
        this.idExperto = idExperto;
    }
    public Integer getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }




}


